### ISSUE TITLE
PL03000006 The transaction date 'Array' is invalid.

### ISSUE THREAD

**Issue by billystalnaker** [Intacct/intacct-sdk-php#121]
```php
$transaction_date = new DateType(gmdate('Y-m-d', strtotime($sales_order->created_datetime)), new \DateTimeZone('UTC'));
$query->setTransactionDate($transaction_date);
```
```xml
<function controlid="sales_order-Qih4QzDXGn">
  <create_sotransaction>
    <transactiontype>Sales Order</transactiontype>
    <datecreated>
      <year>2017</year>
      <month>07</month>
      <day>25</day>
    </datecreated>
    <customerid>107-100</customerid>
    <customfields>
      <customfield>
        <customfieldname>CRUXOS_ID</customfieldname>
        <customfieldvalue>3-100</customfieldvalue>
      </customfield>
    </customfields>
    <projectid>8271-S-9703-J-100</projectid>
    <sotransitems>
      <sotransitem>
        <itemid>30-100</itemid>
        <quantity>50</quantity>
        <unit>My New Unit</unit>
        <price>12.00</price>
        <locationid>100</locationid>
        <customfields>
          <customfield>
            <customfieldname>CRUXOS_ID</customfieldname>
            <customfieldvalue>55-100</customfieldvalue>
          </customfield>
        </customfields>
        <projectid>8271-S-9703-J-100</projectid>
        <customerid>107-100</customerid>
      </sotransitem>
    </sotransitems>
  </create_sotransaction>
</function>
```

I'm not sure why I'm getting this error. All I do is provide the DateType to the Query..

**Comment by jimmymcpeter** [comment]
What class does `$query` represent?

**Comment by billystalnaker** [comment]
`$query` is an instance of `OrderEntryTransactionCreate`.

**Comment by jimmymcpeter** [comment]
Hi @billystalnaker, I can't reproduce this.  The XML you pasted above, is that from a log?  The only thing I could think of is the `XmlWriter::writeDateSplitElements` is screwing up the explode somehow.

**Comment by billystalnaker** [comment]
This is the actual xml when I dump right before sending it to the Intacct.. Am I on a different code base maybe..?

**Comment by jimmymcpeter** [comment]
What's in your composer.json / `composer info` ?

**Comment by billystalnaker** [comment]
```javascript
{...
    "intacct/intacct-sdk-php": "*"
}
```

**Comment by jimmymcpeter** [comment]
Can you run `composer info` from the command line?

Side note - Instead of using `*`, you should really set a version like `1.0.*`.  If I push v2.0 into release, your entire app will break the next time you run `composer update`.

**Comment by billystalnaker** [comment]
```
intacct/intacct-sdk-php                  v1.0.5  Intacct SDK for PHP
```

**Comment by billystalnaker** [comment]
Output from a debug in XMLWriter
```
DateType: object(Intacct\FieldTypes\DateType)#1283 (3) {
  ["date"]=>
  string(26) "2017-08-01 00:00:00.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(3) "UTC"
}
string(10) "Year: 2017"

string(9) "Month: 08"

string(7) "Day: 01"

Function: Intacct\Xml\XMLWriter -> writeDateSplitElements | Line: 131 Timestamp: 1502736033
```

**Comment by billystalnaker** [comment]
Ok, I know why you couldn't replicate the issue. For some unknown reason to me it only screams at me when I'm importing other objects in the same transaction for whatever reason.. My entire content is as follows:
```xml
<content>
  <function controlid="project-rollup-nKi5JMbA0A">
    <update>
      <project>
        <projectid>64-P-100</projectid>
        <name>Administrative</name>
        <projectcategory>Contract</projectcategory>
        <description>Administrative</description>
        <customerid>107-100</customerid>
        <begindate>10/01/2012</begindate>
        <enddate>09/30/2017</enddate>
        <locationid>100</locationid>
        <prj_business_line></prj_business_line>
        <prj_style></prj_style>
        <prj_category></prj_category>
        <prj_staffing_style></prj_staffing_style>
      </project>
    </update>
  </function>
  <function controlid="job-Q1Si-vPjZH">
    <create>
      <project>
        <projectid>8272-S-9704-J-100</projectid>
        <name>Administrative:Admin Time</name>
        <projectcategory>Contract</projectcategory>
        <parentid>64-P-100</parentid>
        <invoicewithparent>true</invoicewithparent>
        <customerid>107-100</customerid>
        <shipto>
          <contactname>2334-100</contactname>
        </shipto>
        <begindate>07/24/2017</begindate>
        <enddate>08/01/2017</enddate>
        <locationid>100</locationid>
        <prj_business_line>Overhead</prj_business_line>
        <prj_style>Overhead</prj_style>
        <prj_category>Overhead</prj_category>
        <prj_staffing_style>In-House</prj_staffing_style>
        <prj_store_number></prj_store_number>
        <prj_retailer>ProVantage Corp</prj_retailer>
        <prj_store_state>NC</prj_store_state>
        <prj_store_city>Raleigh</prj_store_city>
        <prj_store_county>Wake</prj_store_county>
      </project>
    </create>
  </function>
  <function controlid="item-yWn6y2mk2Q">
    <create>
      <item>
        <itemid>31-100</itemid>
        <name>My Project Split by Percentage</name>
        <itemtype>Non-Inventory</itemtype>
        <cost_method>Standard</cost_method>
        <extended_description></extended_description>
        <uomgrp>Bay</uomgrp>
        <baseprice>55.00</baseprice>
      </item>
    </create>
  </function>
  <function controlid="sales_order-O-k0ZPQLMB">
    <create_sotransaction>
      <transactiontype>Sales Order</transactiontype>
      <datecreated>
        <year>2017</year>
        <month>08</month>
        <day>1</day>
      </datecreated>
      <customerid>107-100</customerid>
      <customfields>
        <customfield>
          <customfieldname>CRUXOS_ID</customfieldname>
          <customfieldvalue>5-100</customfieldvalue>
        </customfield>
      </customfields>
      <projectid>8272-S-9704-J-100</projectid>
      <sotransitems>
        <sotransitem>
          <itemid>31-100</itemid>
          <quantity>12</quantity>
          <unit>Bay</unit>
          <price>55.00</price>
          <locationid>100</locationid>
          <customfields>
            <customfield>
              <customfieldname>CRUXOS_ID</customfieldname>
              <customfieldvalue>56-100</customfieldvalue>
            </customfield>
          </customfields>
          <projectid>8272-S-9704-J-100</projectid>
          <customerid>107-100</customerid>
        </sotransitem>
      </sotransitems>
    </create_sotransaction>
  </function>
</content>
```
Running each one individually works fine. But when ran as a bulk transaction like this it fails. Any help would be appreciated.

**Comment by jimmymcpeter** [comment]
I don't know man.  Looking at this, you wrote your own project/items functions and did not use the SDK's because all of the fields would be in uppercase.  I would load your code up in XDebug and throw a breakpoint on the various date fields you're attempting to writeElement on.

**Comment by billystalnaker** [comment]
Hmm... I am using the SDK's files... They're written in lower case..
example file OrderEntryTransactionCreate.php
```php
<?php

/**
 * Copyright 2017 Intacct Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"). You may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * or in the "LICENSE" file accompanying this file. This file is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

namespace Intacct\Functions\OrderEntry;

use Intacct\Xml\XMLWriter;
use InvalidArgumentException;

/**
 * Create a new order entry transaction record
 */
class OrderEntryTransactionCreate extends AbstractOrderEntryTransaction
{

    /**
     * Write the function block XML
     *
     * @param XMLWriter $xml
     */
    public function writeXml(XMLWriter &$xml)
    {
        $xml->startElement('function');
        $xml->writeAttribute('controlid', $this->getControlId());

        $xml->startElement('create_sotransaction');

        $xml->writeElement('transactiontype', $this->getTransactionDefinition(), true);

        $xml->startElement('datecreated');
        $xml->writeDateSplitElements($this->getTransactionDate(), true);
        $xml->endElement(); //datecreated

        if ($this->getGlPostingDate()) {
            $xml->startElement('dateposted');
            $xml->writeDateSplitElements($this->getGlPostingDate(), true);
            $xml->endElement(); //dateposted
        }

        $xml->writeElement('createdfrom', $this->getCreatedFrom());
        $xml->writeElement('customerid', $this->getCustomerId(), true);
        $xml->writeElement('documentno', $this->getDocumentNumber());

        if ($this->getOriginalDocumentDate()) {
            $xml->startElement('origdocdate');
            $xml->writeDateSplitElements($this->getOriginalDocumentDate(), true);
            $xml->endElement(); //origdocdate
        }
...
```

**Comment by jimmymcpeter** [comment]
I'm referring the project and item.

**Comment by billystalnaker** [comment]
Hmm, that is weird that they're lower case there.. I don't use any special files for items or projects..

**Comment by billystalnaker** [comment]
Like I said if there is more than one other function in the transaction, it fails, otherwise it goes through no problem. I'll submit a ticket with Intacct and see what they say..
Non-working XML:
```xml
<content>
  <function controlid="job-Q1Si-vPjZH">
    <create>
      <project>
        <projectid>CUSTOM_JOB-1</projectid>
        <name>Administrative:Admin Time</name>
        <projectcategory>Contract</projectcategory>
        <parentid>64-P-100</parentid>
        <invoicewithparent>true</invoicewithparent>
        <customerid>107-100</customerid>
        <shipto>
          <contactname>2334-100</contactname>
        </shipto>
        <begindate>07/24/2017</begindate>
        <enddate>08/01/2017</enddate>
        <locationid>100</locationid>
        <prj_business_line>Overhead</prj_business_line>
        <prj_style>Overhead</prj_style>
        <prj_category>Overhead</prj_category>
        <prj_staffing_style>In-House</prj_staffing_style>
        <prj_store_number></prj_store_number>
        <prj_retailer>ProVantage Corp</prj_retailer>
        <prj_store_state>NC</prj_store_state>
        <prj_store_city>Raleigh</prj_store_city>
        <prj_store_county>Wake</prj_store_county>
      </project>
    </create>
  </function>
  <function controlid="sales_order-O-k0ZPQLMB">
    <create_sotransaction>
      <transactiontype>Sales Order</transactiontype>
      <datecreated>
        <year>2017</year>
        <month>08</month>
        <day>1</day>
      </datecreated>
      <customerid>107-100</customerid>
      <projectid>CUSTOM_JOB-1</projectid>
      <sotransitems>
        <sotransitem>
          <itemid>31-100</itemid>
          <quantity>12</quantity>
          <unit>Bay</unit>
          <price>55.00</price>
          <locationid>100</locationid>
          <projectid>CUSTOM_JOB-1</projectid>
          <customerid>107-100</customerid>
        </sotransitem>
      </sotransitems>
    </create_sotransaction>
  </function>
</content>
```
Response:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<response>
  <control>
    <status>success</status>
    <senderid>Rosewood</senderid>
    <controlid>testRequestId</controlid>
    <uniqueid>false</uniqueid>
    <dtdversion>3.0</dtdversion>
  </control>
  <operation>
    <authentication>
      <status>success</status>
      <userid>999</userid>
      <companyid>Rosewood-DEV</companyid>
      <sessiontimestamp>2017-08-15T10:49:20-07:00</sessiontimestamp>
    </authentication>
    <result>
      <status>aborted</status>
      <function>create</function>
      <controlid>job-Q1Si-vPjZH</controlid>
      <data listtype="objects" count="1">
        <project>
          <RECORDNO>285</RECORDNO>
          <PROJECTID>CUSTOM_JOB-1</PROJECTID>
        </project>
      </data>
    </result>
    <result>
      <status>aborted</status>
      <function>create_sotransaction</function>
      <controlid>sales_order-O-k0ZPQLMB</controlid>
      <errormessage>
        <error>
          <errorno>PL03000006</errorno>
          <description></description>
          <description2>The transaction date &#039;Array&#039; is invalid.</description2>
          <correction></correction>
        </error>
        <error>
          <errorno>BL01001973</errorno>
          <description></description>
          <description2>Error preparing values!</description2>
          <correction></correction>
        </error>
        <error>
          <errorno>BL01001973</errorno>
          <description></description>
          <description2>Could not create Document record!</description2>
          <correction></correction>
        </error>
        <error>
          <errorno>XL03000009</errorno>
          <description></description>
          <description2>The entire transaction in this operation has been rolled back due to an error.</description2>
          <correction></correction>
        </error>
      </errormessage>
    </result>
  </operation>
</response>
```

Working XML:
```xml
<content>
  <function controlid="sales_order-O-k0ZPQLMB">
    <create_sotransaction>
      <transactiontype>Sales Order</transactiontype>
      <datecreated>
        <year>2017</year>
        <month>08</month>
        <day>1</day>
      </datecreated>
      <customerid>107-100</customerid>
      <projectid>64-P-100</projectid>
      <sotransitems>
        <sotransitem>
          <itemid>31-100</itemid>
          <quantity>12</quantity>
          <unit>Bay</unit>
          <price>55.00</price>
          <locationid>100</locationid>
          <projectid>64-P-100</projectid>
          <customerid>107-100</customerid>
        </sotransitem>
      </sotransitems>
    </create_sotransaction>
  </function>
</content>
```
Response:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<response>
  <control>
    <status>success</status>
    <senderid>Rosewood</senderid>
    <controlid>testRequestId</controlid>
    <uniqueid>false</uniqueid>
    <dtdversion>3.0</dtdversion>
  </control>
  <operation>
    <authentication>
      <status>success</status>
      <userid>999</userid>
      <companyid>Rosewood-DEV</companyid>
      <sessiontimestamp>2017-08-15T10:50:27-07:00</sessiontimestamp>
    </authentication>
    <result>
      <status>success</status>
      <function>create_sotransaction</function>
      <controlid>sales_order-O-k0ZPQLMB</controlid>
      <key>Sales Order-SO-0054</key>
    </result>
  </operation>
</response>
```

**Comment by jimmymcpeter** [comment]
@billystalnaker This might be a product issue, not an SDK issue.  Would you please open a case with Sage Intacct Support and add a comment that it may be related to ticket 69125 ?

**Comment by kuldip1** [comment]
Hi @jimmymcpeter 

I am getting same error on php API side.

Fatal error: Uncaught TypeError: Intacct\Xml\XMLWriter::writeDateSplitElements(): Argument #1 ($date) must be of type DateTime, null given, called in D:\Projects\CustomPHP\intacct\vendor\intacct\intacct-sdk-php\src\Intacct\Functions\InventoryControl\InventoryTransactionCreate.php on line 44 and defined in D:\Projects\CustomPHP\intacct\vendor\intacct\intacct-sdk-php\src\Intacct\Xml\XMLWriter.php:142 Stack trace: #0 D:\Projects\CustomPHP\intacct\vendor\intacct\intacct-sdk-php\src\Intacct\Functions\InventoryControl\InventoryTransactionCreate.php(44): Intacct\Xml\XMLWriter->writeDateSplitElements(NULL, true) #1 D:\Projects\CustomPHP\intacct\vendor\intacct\intacct-sdk-php\src\Intacct\Xml\Request\OperationBlock.php(141): Intacct\Functions\InventoryControl\InventoryTransactionCreate->writeXml(Object(Intacct\Xml\XMLWriter)) #2 D:\Projects\CustomPHP\intacct\vendor\intacct\intacct-sdk-php\src\Intacct\Xml\RequestBlock.php(115): Intacct\Xml\Request\OperationBlock->writeXml(Object(Intacct\Xml\XMLWriter)) #3 D:\Projects\CustomPHP\intacct\vendor\intacct\intacct-sdk-php\src\Intacct\Xml\RequestHandler.php(144): Intacct\Xml\RequestBlock->writeXml() #4 D:\Projects\CustomPHP\intacct\vendor\intacct\intacct-sdk-php\src\Intacct\AbstractClient.php(97): Intacct\Xml\RequestHandler->executeOnline(Array) #5 D:\Projects\CustomPHP\intacct\vendor\intacct\intacct-sdk-php\src\Intacct\OnlineClient.php(36): Intacct\AbstractClient->executeOnlineRequest(Array, Object(Intacct\RequestConfig)) #6 D:\Projects\CustomPHP\intacct\crud-inventory.php(50): Intacct\OnlineClient->execute(Object(Intacct\Functions\InventoryControl\InventoryTransactionCreate)) #7 {main} thrown in D:\Projects\CustomPHP\intacct\vendor\intacct\intacct-sdk-php\src\Intacct\Xml\XMLWriter.php on line 142

I have create Inventory using method InventoryTransactionCreate();

Thanks
